### ISSUE TITLE
Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.

### ISSUE THREAD

**Issue by atloss** [hipay/hipay-enterprise-shopware-6#1]
**Describe the bug**
This extension doesn't allow apps, that are based on shopware 6's [app system](https://developer.shopware.com/docs/guides/plugins/apps), to be installed/uninstalled correctly. The following error appears on installation/uninstallation of such apps:

"Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it."

**To Reproduce**
1. Install this extension
2. Install an app, that is based on the app system. E.g. shopware's [pop up extension](https://store.shopware.com/en/swag497523782235f/custom-popups-notifications.html)
3. The installation and activation is correct
4. Now, uninstall the app and click "remove app data permanently"
5. The error above appears.

**Expected behavior**
No issue appears and the uninstallation process of the app works correctly.

**Additional context**
I have seen this issue a couple of times already. Sometimes the issue appears on installation, sometimes on uninstallation of apps. Especially on installation this is a major compatibility issue with apps, since they are not correctly embedded into shopware, because template files (html.twig) cannot be written into the corresponding database table.

Origin: In `HiPay\Payment\Migration\Migration.php` you are using ENUM data types, which Shopware doesn't fully support.

If you need more info, feel free to contact me any time:  luca@atloss.de (Luca Hollenbach)

**Comment by JBaptisteLvt** [comment]
Hello !

Thank you for this bug report, we will add the fix to our ROADMAP ASAP !

**Comment by stormwind85** [comment]
This has been fixed on version 1.0.3 ~> https://github.com/hipay/hipay-enterprise-shopware-6/releases/tag/1.0.3
